### ISSUE TITLE
Does not work on Safari

### ISSUE THREAD

**Issue by tommy2d** [simplesamlphp/simplesamlphp-module-webauthn#23]
Even on the latest Safari Technology Preview, the following error triggers when clicking on the authenticate button in the Two Factor Identification step:

`
NotAllowedError: This request has been voided by a new request.
get
authButtonClick — webauthn.js:44
`

**Comment by restena-sw** [comment]
Hello,

to my knowledge, WebAuthn is supported on Safari on macOS only, not on iOS. On macOS, it is part of the production release of Safari and there is no need (and maybe some harm) in using a Technology Preview version.

Also, to try and replicate any problems, it would be useful to know what your WebAuthn token actually is. Is it a USB token or did you try TouchID?

You can always cross-check if what you are trying to do actually works across implementations by checking the various demo sites such as https://webauthn.io .

If those also don't work, I don't think we can blame our code.

**Comment by tommy2d** [comment]
The example also does not work with my Yubikey 5CI combined with safari. I have a hard time figuring out who's at fault here, Yubico or Apple.  It's hard to imagine apple would release this functionality in Safari without it working  on a general demo site, but other browsers do seem to be working.

**Comment by restena-sw** [comment]
Thanks for the update. Again, you still say "Safari" not making clear if this is iOS/iPadOS Safari or desktop safari.
Anyway, since this is apparently a browser-side problem and not with our code, I will close the issue for now.

Please re-open it in case the demo sites start working but our code continues not to.

**Comment by tommy2d** [comment]
It’s about the desktop browser. The iOS browser shows a neat not-supported message when using webauthn.io.
