### ISSUE TITLE
Implement passwordless authentication

### ISSUE THREAD

**Issue by joostd** [simplesamlphp/simplesamlphp-module-webauthn#3]
FIDO2 tokens support passwordless use-cases, where resident credentials are used together with a user id (i.e. stored on the token itself instead of wrapped in a key handle on the server).

This could be added with an Auth Source implementation in this module. Compare with 
https://github.com/SURFnet/simplesamlphp-module-authtiqr/blob/develop/lib/Auth/Source/Tiqr.php

**Comment by restena-sw** [comment]
It's a pity that authprocfilters are always run /after/ the main authentication. Otherwise, the module could check to see if it is called pre-authenticated or post-authenticated, and if pre, switch to the resident credentials mode. If called post- it would use the knowledge of the authenticated user and behave like it does now.

Since that's not how things work, I guess this mode of operation only works when being an authsource, i.e. in what #4 suggests.

**Comment by restena-sw** [comment]
I'm taking first baby steps towards supporting this. 

First, we need to make sure that keys are registered in a way that allows Passwordless to function: the registration needs to set "residentKey=required" (which possibly limits the vendor/model list for that use case; but Passwordless can't possibly function without resident keys).

Second, I would like to set "userVerification=required" too. Passwordless is only really secure if loss of the physical token does not open the doors to attackers to log in with a push of a button. This again may limit the vendor/model list to those supporting userVerification. And it also means that some keys will become more inconvenient than before (e.g. Yubikey 5 sending the user through an extra round of "type PIN at computer keyboard and push button a second time" at every auth). But I believe it would be too negligent to allow passwordless without UV.

With those two being set, what remains is the unsolved privacy problem around storage and enumeration of sites with a resident key: if the physical token is lost, an attacker can read the list of scopes and usernames as metainfo about the resident credential. So, while they can not use the UV-enabled token to actually log in and impersonate, some info about the user and their associated accounts leaks.

I read about an extension to request that the metainfo is not revealed by token management tools unless the user UVed  (e.g. at https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/Resident_Keys.html // Credential Protection .This sounds like a useful privacy extension, but I wonder if this is really standardised vs. vendor-specific, whether it is safe to set it to the value userVerificationRequired . I'll investigate this as I go, hoping that it won't make too many vendors/models unusable if they don't support this.

Happy for any and all comments!

**Comment by restena-sw** [comment]
Ah, found it just after submitting. This credProtect feature is not part of CTAP2, but is in CTAP2.1. 
Not sure how widespread CTAP 2.1 already is... let's see.

**Comment by joostd** [comment]
Just some additional information to update this ticket:

Regarding passwordless:
- This is great timing as multi-device credentials as implemented by Apple on iOS16 and MacOS 13 (later this month), Google on Android (later this year), and Microsoft (sometime in the future).
- Yes, passwordless implies *resident keys*, or *discoverable credentials* as they are called in [Webauthn level 2](https://www.w3.org/TR/webauthn-2/#discoverable-credential), and discoverable credentials imply User Verification.
- Often the more popular term *passkeys* is used. Multi-device credentials are a specific type of passkeys that can be synchronised which makes them interesting for consumer use cases, but perhaps less so for enterprise use cases. Maybe we need to think of some form of configurable policy here?
- There is work being done by the [W3C WebAuthn Community Adoption Group](https://www.w3.org/community/webauthn-adoption/) and the [FIDO Alliance](https://fidoalliance.org/) on a [developer website for passkeys](https://passkeydeveloper.github.io/passkeys.dev/) 

Regarding credProtect:
- I would suggest a configuration option for the credentialProtectionPolicy level (userVerificationOptional, userVerificationOptionalWithCredentialIDList, userVerificationRequired) with the first one being the default.
- You can demo/test the credProtect extension here: aka.ms/webauthntest
- All YubiKeys with [firmware version 5.2.3](https://support.yubico.com/hc/en-us/articles/360016649319-YubiKey-5-2-3-Enhancements-to-FIDO-2-Support) and later support the credProtect extension. I am not sure about security keys by other vendors, although other vendors have obtained CTAP 2.1 certification (e.g. [Feitian](https://www.ftsafe.com/article/821.html) and [AuthenTrend](https://authentrend.com/atkeypro-is-fido-ctap2-1-certified/))
- [libfido2](https://developers.yubico.com/libfido2/) has a tool to check any FIDO2 security key for credProtect support (using CTAP2 on the command line, not using WebAuthn through the browser):

```bash
$ fido2-token -I "$(fido2-token -L | cut -d: -f1-2)" | grep extension
extension strings: credProtect, hmac-secret
```

And lastly:
The will also be browser support for hybrid use cases where passwords and passkeys can be used from the same web page (for instance while migrating users away from passwords). See the recently published guidance on [Autofill](https://developers.yubico.com/WebAuthn/Concepts/Passkey_Autofill/)

**Comment by restena-sw** [comment]
Meanwhile, I implemented the game mechanics to require residentKeys and UV on registration if you want to go passwordless.

Both my YubiKey Bio FIDO Edition and my Feitian K27 returned automatically (i.e. without requesting) that they secured the resident key with credProtect = 2 (userVerificationRequired).

So, that level seems to be implemented and common and the default. Makes me think that making this configurable is even too forgiving - we could go towards always requiring it, considering that keys just do it anyway.

Thanks for all those pointers to test suites. Very welcome!

**Comment by restena-sw** [comment]
The acceptance of a Passkeys "shared" credential or not is much rather something to make configurable. Personally I very much dislike the thought of handing over the private key to a big brother of choice, and wouldn't want to bet my enterprise security on a third party's trustworthiness. (Yes, I'm aware of the counterargument that you already put your trust in them if you use their authenticators at all. But still.)

**Comment by restena-sw** [comment]
The master branch now has both a pure Passwordless authsource, as well as a "hybrid" that allows a user to choose typing a u/p or using a Passwordless (same page, same entityID). This takes into account all the things mentioned in this issue; closing it.
