### ISSUE TITLE
Routes.yaml can't be found

### ISSUE THREAD

**Issue by faragom** [simplesamlphp/simplesamlphp-module-webauthn#32]
The master version of the module which has been migrated to controllers has the routes file on a location different from what simple SAML expects (the root of the module):

Actual location:
`/routing/routes/routes.yaml`

Expected location:
`/routes.yaml`

**Comment by tvdijen** [comment]
This week SimpleSAML 1.19 will be released where the location was changed to `/routing/routes/`, so the location is correct.
