### ISSUE TITLE
Implement a standalone registration page.

### ISSUE THREAD

**Issue by joostd** [simplesamlphp/simplesamlphp-module-webauthn#4]
Currently, registration is integrated in an authentication processing filter. A standalone registration page could be used with an SP you  can configure to require some other authsource.

The use-case is to let everyone with a sufficiently strong way of authentication to register an alternative (a FIDO2 authenticator in this case). This way anyone with, say an X.509 certificate used for authentication, can register an authenticator to subsequently use on systems that don't have that certificate installed.

An alternative use case: let users authenticate using a username and password from a restricted range of IP Addresses, and require a FIDO2 authenticator outside that range. This allows for on-premise registration of authenticators, to use them when login in from untrusted networks.

**Comment by restena-sw** [comment]
Those are quite compelling use cases. Unfortunately, I was happy being able to program an authprocfilter and am not sure if I'm to do an authsource.

The good thing is that despite the integration work into SSP as such, the technical side is fairly simple: create a button with the JavaScript actions found in www/webauthn.php ($t->data['regForm'] and the lines below defining var publicKeyCredentialCreationOptions).

POST the result of the call to a page, and feed the values into a new WebAuthnRegistrationEvent().

Right now, the final steps of signup (making sure it's not a duplicate and updating the credentials database) are done in www/regprocess.php. If the authsource does the same things, it may make sense to pull that code into the class instead.

**Comment by melanger** [comment]
This was addressed in #30
