### ISSUE TITLE
Cannot register new device

### ISSUE THREAD

**Issue by vinay-athiyil** [simplesamlphp/simplesamlphp-module-webauthn#54]
I have configured webauthn plugin as a auth process filter. After login SSO redirected to registration page. System confirmed device verification and got following exception.

PHP version: 8.1

The debug information below may be of interest to the administrator / help desk:

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 public/_include.php:31 (SimpleSAML_exception_handler)
1 vendor/symfony/error-handler/ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: TypeError: Cannot assign string to property SimpleSAML\Module\webauthn\WebAuthn\WebAuthnAbstractEvent::$algo of type int
Backtrace:
7 modules/webauthn/src/WebAuthn/WebAuthnRegistrationEvent.php:558 (SimpleSAML\Module\webauthn\WebAuthn\WebAuthnRegistrationEvent::validateAttestedCredentialData)
6 modules/webauthn/src/WebAuthn/WebAuthnRegistrationEvent.php:89 (SimpleSAML\Module\webauthn\WebAuthn\WebAuthnRegistrationEvent::__construct)
5 modules/webauthn/src/Controller/RegProcess.php:124 (SimpleSAML\Module\webauthn\Controller\RegProcess::main)
4 vendor/symfony/http-kernel/HttpKernel.php:163 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
3 vendor/symfony/http-kernel/HttpKernel.php:75 (Symfony\Component\HttpKernel\HttpKernel::handle)
2 vendor/symfony/http-kernel/Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
1 src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
0 public/module.php:14 (N/A)

**Comment by tvdijen** [comment]
@restena-sw Would it be safe to declare the constants as integers? Because now they are strings while the code expects integers.

**Comment by restena-sw** [comment]
Is the OP working with master? I believe this was fixed a while ago...

**Comment by vinay-athiyil** [comment]
It is working with master branch. Is there any release planned for this fix?

**Comment by restena-sw** [comment]
Glad to hear that.

I am thinking of making a 2.1.0 from current master soon. There's currently one issue pending on my list, about a config parameter that is in the module config but should more logically be in the authsource config. That's probably only a one-liner or little more; but I'm really short on time currently.

**Comment by restena-sw** [comment]
This parameter placement change is now done, and a release of 2.1.0 is imminent.

**Comment by restena-sw** [comment]
Closing because complete.
