### ISSUE TITLE
composer.json needs version bump for simplesamlphp/assert

### ISSUE THREAD

**Issue by atomicom** [simplesamlphp/simplesamlphp-module-webauthn#55]
Fresh install of SSP 2.0.6 and I'm unable to install both the ldap module and webauthn module because this one has locked "simplesamlphp/assert" to version 0.8.0

```
Problem 1
    - simplesamlphp/simplesamlphp-module-webauthn[v2.1.0, ..., v2.1.1] require simplesamlphp/assert ^0.8.0 -> found simplesamlphp/assert[v0.8.0] but it conflicts with your root composer.json require (^1.0).
```

**Comment by tvdijen** [comment]
You have installed using `composer update` instead of `composer install`, or this would never happened..

**Comment by atomicom** [comment]
sorry forgive my ignorance here but does that mean that I won't be able to run both this module and the ldap module together?
SSP 2.0.6 allows for simplesamlphp/assert ^0.8.0 or ^1.0.0 in its json file but the ldap module only allows for simplesamlphp/assert ^1.0.0

**Comment by atomicom** [comment]
yes thank you for your help. 
Like you said I must have done an update the first time around in trying to get the ldap module working. I started fresh again and installed this module first which worked without a hitch. According to the ldap module releases page, the latest release was v2.0.0 which didn't work. So after you pointed out that their v2.1 had a compatible composer.json I foolishly realized I could specify other tags when doing a composer require, even if they weren't made into official releases.

**Comment by tvdijen** [comment]
You don't have to specify a version at all.. Composer will always get you a compatible version.
Glad it all worked out!
