### ISSUE TITLE
Language Strings are not displayed properly

### ISSUE THREAD

**Issue by libregeek** [simplesamlphp/simplesamlphp-module-webauthn#60]
The language strings in the Webauthn module are not displayed properly. Please see the screenshot:
<img width="817" alt="Screenshot 2023-11-23 190454" src="https://github.com/simplesamlphp/simplesamlphp-module-webauthn/assets/145110/c99e5072-2a20-4775-a9d4-06da56a416b6">

I am using the master branch from Github. SimpleSAMLPHP version is v2.1.0 running on PHP v8.1. Is there any configuration I need to set?

**Comment by tvdijen** [comment]
You have to build the translation-files. `bin/translations translations:update:binary`
This is normally done automatically when you run `composer install`.. How are you deploying?

**Comment by tvdijen** [comment]
We're happy to assist you with proper installation instructions on Slack or on our mailing list.
